# Generated by Django 5.2.4 on 2025-07-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
